<?php

namespace ContainerXbIO9JO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFindNumberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\FindNumber' shared autowired service.
     *
     * @return \App\Controller\FindNumber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'FindNumber.php';

        return $container->services['App\\Controller\\FindNumber'] = new \App\Controller\FindNumber();
    }
}
