<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNSlwYpy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNSlwYpy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNSlwYpy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNSlwYpy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNSlwYpy\App_KernelDevDebugContainer([
    'container.build_hash' => 'NSlwYpy',
    'container.build_id' => '480797dd',
    'container.build_time' => 1610130469,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNSlwYpy');
